version: "3"

services:
  chats-users-gateway:
    build:
      dockerfile: docker/Dockerfile.dev
      context: .
    ports:
      - 8007:8007
    env_file:
      - .env.dev
    networks:
      - chack-check-network

networks:
  chack-check-network:
    name: chack-check-network
    external: true